services:
  - type: web
    name: my-django-app
    env: python
    plan: free  # Puedes cambiar esto a un plan de pago según tus necesidades
    buildCommand: |
      pip install -r requirements.txt
      npm install
      npm run build
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn projetmyss.wsgi:application
