# Generated by Django 5.0.4 on 2024-05-01 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPropuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('no_empleado', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=254)),
                ('area', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=70)),
                ('correo_personal', models.EmailField(max_length=254)),
                ('correo_institucional', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('torre_perteneciente', models.CharField(max_length=100)),
                ('compromiso', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('descripcion_respuesta', models.TextField()),
                ('archivo_propuesta', models.TextField()),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_propuesta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propuestas.tipopropuesta')),
            ],
        ),
    ]
