# Generated by Django 5.0.4 on 2024-05-11 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Motivo', models.CharField(max_length=200)),
                ('Asunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.asunto')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comentarios', models.CharField(max_length=100)),
                ('Motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.motivo')),
            ],
        ),
    ]
