# Generated by Django 5.0.4 on 2024-05-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_asunto_motivo_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motivo',
            old_name='Motivo',
            new_name='Descripcion',
        ),
        migrations.AddField(
            model_name='asunto',
            name='Abreviatura',
            field=models.CharField(default='Titulo', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motivo',
            name='Titulo',
            field=models.CharField(default='titulo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asunto',
            name='Tipo',
            field=models.CharField(max_length=20),
        ),
    ]
