from .revision_documentos import RevisionDocumentosView
from .envio_documentos import EnvioDocumentosView
from .propuestas_detalles import PropuestasDetallesView
from .rechazar_propuesta import RechazarPropuestaView
