from .revision_documentos import RevisionDocumentosView
from .envio_documentos  import EnvioDocumentosView
from .propuestas_detalles import PropuestasDetallesView
from .propuestas_detalles import PropuestasDetallesView

